// Prompty dla generatora — skopiowane z src/lib/prompts.ts
// Format: getPrompt(climate, variant, photoIndex 0-8)

type PromptMap = Record<string, Record<string, string[]>>;

const PROMPTS: PromptMap = {
  city: {
    "paris-luxury": [
      "Elegant woman walking on Champs-Élysées, Paris, morning golden light, luxury boutiques background, haute couture look, full body shot",
      "Fashion editorial portrait near Eiffel Tower, soft natural light, sophisticated Parisian style, medium shot",
      "Luxury fashion look outside Dior boutique Paris, confident pose, wide angle street photography",
      "Woman in elegant attire at Parisian café terrace, warm afternoon light, editorial fashion shot",
      "Side profile walking along Seine river Paris, elegant silhouette, blue hour light",
      "Close up portrait, Paris streets background, glamorous makeup, haute couture details",
      "Dynamic editorial walk on cobblestone Paris alley, motion blur background, luxury fashion",
      "Seated elegantly at outdoor café Paris, black and white editorial feel, fashion photography",
      "Full body fashion shot, Grand Palais background, golden hour, editorial luxury magazine style",
    ],
    "corporate-glass": [
      "Powerful woman in front of glass skyscraper, corporate fashion editorial, strong confident pose",
      "Business fashion portrait in modern glass lobby, sharp tailored suit, professional editorial",
      "Dynamic shot walking through financial district, glass buildings reflection, power dressing",
      "Close up portrait, modern office glass reflection, sharp makeup, corporate chic",
      "Full body shot, glass elevator lobby, polished executive look, architectural editorial",
      "Editorial fashion against glass curtain wall, reflections, abstract urban background",
      "Confident pose on rooftop of glass building, city skyline, power woman editorial",
      "Side profile in modern glass corridor, clean lines, minimalist fashion editorial",
      "Looking up at glass tower, dynamic angle, corporate fashion, strong lighting",
    ],
    "nyc-power": [
      "Woman striding across Manhattan crosswalk, NYC taxis background, dynamic editorial fashion",
      "Fashion portrait Times Square New York, neon lights bokeh, street editorial photography",
      "Full body shot walking through Central Park NYC, autumn leaves, editorial fashion",
      "Close portrait in Brooklyn Bridge background, golden hour NYC skyline, fashion editorial",
      "Dynamic motion shot on NYC subway platform, editorial fashion photography, urban energy",
      "Rooftop editorial shoot Manhattan skyline, sunset colors, high fashion photography",
      "Street fashion editorial in SoHo NYC, brick walls background, editorial photography",
      "Fashion model walking High Line NYC, city view background, editorial luxury fashion",
      "Night fashion editorial Times Square, light trails, NYC electric energy, full body shot",
    ],
    "motion-editorial": [
      "Dynamic fashion editorial in motion, city street background, hair flowing, action shot",
      "Editorial photo of woman in movement, urban background, intentional motion blur, fashion",
      "Running editorial fashion shot city street, dynamic energy, luxury brand campaign feel",
      "Spinning fashion editorial, architectural city background, flowing dress, movement",
      "Fashion editorial jump shot, rooftop city background, editorial magazine quality",
      "Walking fast editorial, wind in hair, blurred city lights background, dynamic fashion",
      "Turning around fashion editorial, golden hour, motion captured, luxury fashion photography",
      "Editorial dance movement urban environment, artistic fashion photography, expression",
      "Close up motion portrait, city lights background, hair in motion, editorial fashion",
    ],
  },
  golden: {
    "amalfi-drive": [
      "Fashion editorial Amalfi Coast Italy, clifftop road, Mediterranean sea, golden hour, full body",
      "Luxury fashion portrait Positano Italy, colorful houses background, warm golden light",
      "Editorial fashion shot on narrow Amalfi road, lemon trees, Italian Riviera aesthetic",
      "Woman at Amalfi cliffside viewpoint, turquoise sea below, editorial luxury fashion",
      "Fashion portrait on terrace overlooking Amalfi coast, bougainvillea, golden afternoon",
      "Walking along Amalfi coastal road, olive trees, warm Mediterranean light, full body editorial",
      "Close portrait golden hour Amalfi, sea sparkle background, Italian luxury fashion",
      "Seated on Amalfi terrace steps, colorful ceramics, editorial fashion photography",
      "Full body fashion shot Ravello gardens Amalfi, golden light, luxury Italian editorial",
    ],
    "botanical-garden": [
      "Elegant woman in lush botanical garden, tropical plants, morning light, editorial fashion",
      "Fashion portrait surrounded by exotic flowers botanical garden, soft natural light",
      "Full body editorial in greenhouse botanical garden, green glass ceiling, plants surrounding",
      "Close up portrait among tropical leaves, dappled light botanical garden, fashion editorial",
      "Walking through botanical garden path, flowering trees, golden morning light, full body",
      "Seated on stone bench botanical garden, roses background, editorial fashion photography",
      "Fashion editorial in Japanese garden section, bridge, koi pond background, serene",
      "Portrait amid giant palms botanical garden, dramatic vertical composition, fashion",
      "Golden hour botanical garden meadow, wildflowers, flowing fabric, editorial fashion shot",
    ],
    "mediterranean-rocks": [
      "Woman standing on Mediterranean sea rocks, turquoise water, golden sunset, editorial fashion",
      "Fashion portrait on rocky coastline, crashing waves, dramatic sky, luxury editorial",
      "Full body shot rocky Mediterranean shore, warm pink light, editorial fashion photography",
      "Sitting on rocks overlooking Mediterranean, sunset colors, flowing dress, editorial",
      "Close portrait rocky shore, sea spray, golden light, fashion editorial photography",
      "Walking barefoot rocky beach Mediterranean, sunset, hair flowing, full body editorial",
      "Fashion editorial rocky cliffside, dramatic sea below, golden hour luxury fashion",
      "Reclining on flat Mediterranean rock, turquoise sea, editorial fashion, warm tones",
      "Silhouette against Mediterranean sunset from rocks, editorial fashion, golden backlight",
    ],
    "mountain-sunset": [
      "Fashion editorial alpine meadow, mountain peaks background, pink sunset, full body shot",
      "Portrait at mountain viewpoint, dramatic sunset sky, editorial luxury fashion photography",
      "Walking alpine path sunset, mountain silhouettes, golden pink light, editorial fashion",
      "Seated on mountain rock, valley view, warm sunset tones, editorial fashion portrait",
      "Fashion editorial pine forest mountain, sunset filtering through trees, golden light",
      "Close portrait mountain peak background, dramatic sunset sky, editorial fashion",
      "Full body shot alpine meadow wildflowers, mountain sunset, flowing editorial fashion",
      "Woman at mountain lake, sunset reflection, editorial luxury fashion photography",
      "Dramatic silhouette mountain ridge sunset, editorial fashion, golden backlight full body",
    ],
  },
  gucci: {
    "emerald-garden": [
      "Woman in Gucci-style garden with marble fountain, emerald green surroundings, editorial luxury fashion",
      "Portrait near baroque fountain garden, gold and green aesthetics, Gucci editorial fashion",
      "Full body shot formal Italian garden, topiary hedges, emerald color palette, luxury editorial",
      "Fashion editorial at ornate garden fountain, late afternoon golden light, luxury fashion",
      "Seated on garden stone steps, fountain background, Gucci aesthetic, editorial fashion",
      "Walking formal garden path, sculpted hedges, marble statues, luxury editorial fashion",
      "Close portrait garden, emerald green plants, gold accessories, editorial fashion photography",
      "Fashion editorial Villa garden Italy, cypresses, golden evening light, luxury fashion",
      "Full body shot baroque garden, ornate fountain, sculptural editorial, Gucci aesthetic",
    ],
    "red-velvet-baroque": [
      "Fashion portrait in baroque hall, red velvet walls, crystal chandelier, luxury editorial",
      "Full body shot palatial baroque interior, gold frames mirrors, red velvet, editorial fashion",
      "Close portrait reflection in ornate gold baroque mirror, editorial fashion photography",
      "Seated on baroque throne chair, red velvet interior, candlelight, luxury fashion editorial",
      "Walking ornate baroque corridor, gold details, red walls, editorial fashion photography",
      "Fashion editorial in opera hall, red velvet seats, chandelier light, luxury fashion",
      "Portrait beside gilded baroque fireplace, candlelight warmth, editorial fashion",
      "Full body baroque ballroom, crystal chandeliers, parquet floor, editorial luxury fashion",
      "Dramatic editorial baroque palace exterior, stone facade, golden hour, luxury fashion",
    ],
    "vintage-eccentric": [
      "Eccentric fashion editorial with pink flamingos, tropical garden, Gucci floral aesthetic",
      "Woman holding flamingo in lush tropical garden, floral patterns, editorial eccentricity",
      "Full body shot tropical garden flamingo, maximalist fashion, eccentric editorial luxury",
      "Portrait in floral garden with flamingo, ornate Gucci aesthetic, editorial fashion",
      "Eccentric fashion editorial, woman among flamingos and tropical flowers, garden",
      "Close portrait tropical flowers, flamingo in background, maximalist fashion editorial",
      "Full body maximalist editorial tropical garden, flamingos, floral patterns, luxury",
      "Walking garden path flamingos, exotic flowers, eccentric luxury fashion editorial",
      "Dramatic pose tropical garden, flamingos, ornate floral fashion, editorial photography",
    ],
    "checkerboard-manor": [
      "Fashion editorial English manor checkerboard floor, eccentric luxury aesthetic",
      "Portrait in grand manor hallway, black and white floor, Gucci eccentric editorial",
      "Full body shot stately manor garden, checkerboard patterns, eccentric luxury fashion",
      "Seated in manor library, plaid and check patterns, eccentric British luxury editorial",
      "Fashion editorial manor entrance, stone facade, eccentric luxury, editorial photography",
      "Walking manor grounds, eccentric fashion, English garden, luxury editorial fashion",
      "Close portrait manor interior, ornate wallpaper, Gucci aesthetic, editorial fashion",
      "Full body manor ballroom, geometric patterns, eccentric luxury fashion editorial",
      "Outdoor manor garden, sculptured hedges, eccentric fashion editorial, golden hour",
    ],
  },
  sport: {
    "tennis-vintage": [
      "Vintage tennis fashion editorial on grass court Wimbledon, retro aesthetic, golden light",
      "Portrait with vintage tennis racket, grass court background, retro fashion editorial",
      "Full body vintage tennis outfit, clay court, editorial fashion photography retro",
      "Walking along tennis net, vintage retro fashion, Wimbledon aesthetic, editorial",
      "Seated courtside vintage tennis aesthetic, retro fashion, editorial photography",
      "Close portrait holding vintage tennis racket, fashion editorial, retro elegance",
      "Full body shot vintage tennis court, white fashion, golden afternoon editorial",
      "Dynamic tennis pose vintage aesthetic, retro fashion editorial photography",
      "Editorial fashion tennis club, vintage atmosphere, creamy tones, full body shot",
    ],
    "boxing-power": [
      "Powerful fashion editorial boxing ring, dramatic spotlights, strong feminine pose",
      "Portrait in boxing gym, dramatic lighting, editorial power fashion photography",
      "Full body boxing editorial, gloves held, dramatic shadow, powerful editorial fashion",
      "Close portrait boxing ring lights background, dramatic editorial fashion photography",
      "Woman boxer editorial, training gym, sweat and glamour, fashion editorial power",
      "Dynamic boxing pose editorial fashion, dramatic lighting, female empowerment",
      "Full body boxing ring fashion editorial, dramatic spotlights, strong pose",
      "Walking through boxing gym editorial, bags background, power fashion photography",
      "Dramatic editorial boxing, locker room aesthetic, powerful feminine fashion",
    ],
    "sport-glamour": [
      "Glamorous athletic fashion editorial, stadium background, haute couture meets sport",
      "Portrait athletic glamour, sporty luxury, golden stadium light, editorial fashion",
      "Full body fashion editorial athletic field, luxury sport aesthetic, golden hour",
      "Close portrait athletic glamour fashion, sweat and elegance, editorial photography",
      "Running editorial athletic glamour, stadium background, luxury sport fashion",
      "Fashion editorial gym luxury aesthetic, mirror reflection, glamorous sport fashion",
      "Dynamic athletic pose glamorous fashion editorial, stadium, golden light",
      "Full body athletic glamour editorial, outdoor stadium, fashion photography luxury",
      "Seated stadium glamorous fashion editorial, luxury sport aesthetic, golden tones",
    ],
    "stadium-editorial": [
      "Fashion editorial in empty stadium, dramatic scale, editorial fashion photography",
      "Portrait stadium seats background, vast scale, editorial fashion photography",
      "Full body shot stadium pitch, dramatic perspective, editorial fashion photography",
      "Woman alone in stadium, dramatic scale editorial, luxury fashion photography",
      "Walking stadium concourse, architecture background, editorial fashion photography",
      "Close portrait stadium lights background, night editorial fashion photography",
      "Full body stadium tunnel entrance, dramatic light editorial fashion photography",
      "Dynamic editorial stadium steps, architectural fashion photography",
      "Stadium roof view editorial fashion, dramatic scale, editorial photography",
    ],
    "yoga-wellness": [
      "Serene yoga editorial nature, morning light, wellness fashion photography, peaceful",
      "Portrait yoga meditation nature, soft morning light, wellness editorial fashion",
      "Full body yoga pose nature, sunrise, wellness editorial fashion photography",
      "Close portrait yoga nature, dew on flowers background, serene wellness editorial",
      "Warrior yoga pose nature editorial, mountain view, wellness fashion photography",
      "Seated meditation by water, wellness editorial fashion, golden morning light",
      "Dynamic yoga editorial lush garden, wellness luxury fashion photography",
      "Walking meditation path nature, wellness fashion editorial, soft light",
      "Yoga on wooden deck, lake view, wellness luxury editorial fashion photography",
    ],
  },
  studio: {
    "magazine-glossy": [
      "Vogue-style studio fashion editorial, glossy magazine aesthetic, professional studio light",
      "Glamorous portrait studio, perfect studio lighting, glossy fashion magazine quality",
      "Full body studio fashion editorial, seamless white background, Vogue aesthetic",
      "Close glamorous portrait studio, editorial makeup, glossy magazine quality light",
      "Dynamic studio editorial pose, fashion magazine quality, professional lighting",
      "Full body fashion editorial studio, colored background, glossy luxury magazine",
      "Seated studio fashion editorial, elegant pose, magazine quality photography",
      "Editorial studio portrait, dramatic fashion lighting, glossy luxury aesthetic",
      "Studio fashion editorial, multiple light setup, magazine quality, full body shot",
    ],
    "dark-dramatic": [
      "Dark dramatic studio fashion editorial, chiaroscuro lighting, mysterious elegant woman",
      "Portrait dark studio, rim light, dramatic shadows, editorial dark fashion photography",
      "Full body dark dramatic editorial, low key lighting, mysterious luxury fashion",
      "Close portrait dark studio, single spotlight, dramatic editorial fashion photography",
      "Dark dramatic editorial, smoke and shadow, mysterious fashion photography studio",
      "Full body shot dark background, dramatic backlight, editorial fashion photography",
      "Dark moody studio editorial, candlelight aesthetic, mysterious elegant fashion",
      "Portrait chiaroscuro light studio, dramatic editorial, dark luxury fashion photography",
      "Full body dramatic dark editorial, shadow play, mysterious high fashion studio",
    ],
    "dynamic-chair": [
      "Editorial fashion on designer chair, geometric studio backdrop, dynamic modern pose",
      "Portrait with sculptural designer chair, clean studio, editorial fashion photography",
      "Full body fashion editorial, Eames chair studio, architectural aesthetic, clean light",
      "Dynamic pose on chair studio editorial, geometric background, modern fashion",
      "Close portrait designer chair studio, clean minimal editorial fashion photography",
      "Editorial perched on chair arm, dynamic pose, studio fashion photography",
      "Full body studio editorial designer chair, modern architectural background",
      "Dramatic pose on designer chair, spotlight editorial studio fashion photography",
      "Walking past chairs studio editorial, dynamic modern fashion photography",
    ],
    "clean-white-editorial": [
      "Clean minimal white studio editorial, pure white background, elegant fashion photography",
      "Portrait pure white studio, soft natural studio light, minimalist editorial fashion",
      "Full body white editorial studio, clean minimalist aesthetic, luxury fashion photography",
      "Close portrait white studio, diffused soft light, minimalist editorial fashion",
      "Minimal white studio editorial, negative space, elegant luxury fashion photography",
      "Full body clean white editorial, all white aesthetic, minimalist fashion photography",
      "Dynamic white studio editorial, pure background, modern elegant fashion photography",
      "Seated white studio editorial, clean minimal aesthetic, luxury fashion photography",
      "Full length white studio editorial, pure elegant minimalism, high fashion photography",
    ],
  },
};

export function getPrompt(
  climate: string,
  variant: string,
  index: number
): string {
  const climatePrompts = PROMPTS[climate];
  if (!climatePrompts) {
    return `Fashion editorial photo, ${climate} style, elegant woman, professional photography`;
  }
  const variantPrompts = climatePrompts[variant];
  if (!variantPrompts) {
    return `Fashion editorial photo, ${climate} ${variant} style, elegant woman, professional photography`;
  }
  return variantPrompts[index % variantPrompts.length];
}
